# Generated by Django 3.2.9 on 2022-01-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your name')),
                ('email', models.CharField(max_length=50, verbose_name='Your email')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('birthday', models.CharField(max_length=100, verbose_name='Your birthday')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customer.customer')),
                ('sell_service', models.BooleanField(default=False, verbose_name='Sell services')),
                ('sell_product', models.BooleanField(default=False, verbose_name='Sell products')),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.store')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
